import { CreateSkillDto } from './dto/create-skill.dto';

export const skillData: CreateSkillDto[] = [
  { name: 'Html', image: 'html-initial.png', progress: 100 },
  { name: 'Css', image: 'css-initial.png', progress: 100 },
  { name: 'Bootstrap', image: 'bootstrap-initial.png', progress: 100 },
  { name: 'Tailwind Css', image: 'tailwind-initial.png', progress: 100 },
  { name: 'Javascript', image: 'javascript-initial.png', progress: 100 },
  { name: 'React js', image: 'reactjs-initial.png', progress: 100 },
  { name: 'Redux', image: 'redux-initial.png', progress: 100 },
  { name: 'Zustand', image: 'zustand-initial.png', progress: 100 },
  { name: 'Next js', image: 'nextjs-initial.png', progress: 100 },
  { name: 'Ant design', image: 'ant-initial.png', progress: 100 },
  { name: 'Material ui', image: 'mui-initial.png', progress: 100 },
  { name: 'Github', image: 'github-initial.png', progress: 100 },
  { name: 'Node js', image: 'nodejs-initial.png', progress: 100 },
  { name: 'Express js', image: 'express-initial.png', progress: 100 },
  { name: 'Json web token', image: 'jwt-initial.png', progress: 100 },
  { name: 'Mongo DB', image: 'mongo-initial.png', progress: 100 },
  { name: 'Mysql', image: 'mysql-initial.png', progress: 100 },
  { name: 'Typescript', image: 'typescript-initial.png', progress: 100 },
  { name: 'Nest js', image: 'nestjs-initial.png', progress: 100 },
  { name: 'Redis', image: 'redis-initial.png', progress: 100 },
  { name: 'Docker', image: 'docker-initial.png', progress: 80 },
  { name: 'Nginx', image: 'nginx-initial.png', progress: 80 },
  { name: 'Deployment', image: 'deployment-initial.png', progress: 80 },
];
